on:
  push:
    branches:
      - master

jobs:
  check:
    name: Check per OS
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]
    with:
      runs-on_value: ${{ matrix.os }}
      artifacts_version: ${{ github.sha }}
      catboost_package_version: 1.2.5
    uses: ./.github/workflows/check_per_os.yaml
