on:
  workflow_call:
    inputs:
      runs-on_value:
        required: true
        type: string
      artifacts_version:
        required: true
        type: string
      catboost_package_name:
        required: false
        type: string
        default: catboost_dev
      catboost_package_version:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.runs-on_value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: catboost

      - name: Env setup
        shell: pwsh
        run: |
          New-Item -Path build_native_root/catboost -ItemType Directory
          Set-Location -LiteralPath ${{ github.workspace }}/build_native_root/catboost
          New-Item -Path app -ItemType Directory
          New-Item -Path tools -ItemType Directory

      - if: inputs.runs-on_value == 'ubuntu-latest'
        uses: actions/download-artifact@v4
        with:
          name: catboost-cli-linux-x86_64-${{ inputs.artifacts_version }}
          path: build_native_root/catboost/app/

      - if: inputs.runs-on_value == 'macos-13'
        uses: actions/download-artifact@v4
        with:
          name: catboost-cli-darwin-universal2-${{ inputs.artifacts_version }}
          path: build_native_root/catboost/app/

      - if: inputs.runs-on_value == 'windows-2022'
        uses: actions/download-artifact@v4
        with:
          name: catboost-cli-windows-x86_64-${{ inputs.artifacts_version }}
          path: build_native_root/catboost/app/

      - if: inputs.runs-on_value == 'ubuntu-latest'
        uses: actions/download-artifact@v4
        with:
          name: catboost-test-tools-linux-x86_64-${{ inputs.artifacts_version }}
          path: build_native_root/

      - if: inputs.runs-on_value == 'macos-13'
        uses: actions/download-artifact@v4
        with:
          name: catboost-test-tools-darwin-universal2-${{ inputs.artifacts_version }}
          path: build_native_root/

      - if: inputs.runs-on_value == 'windows-2022'
        uses: actions/download-artifact@v4
        with:
          name: catboost-test-tools-windows-x86_64-${{ inputs.artifacts_version }}
          path: build_native_root/

      - name: Move test tools to canonical place
        shell: pwsh
        run: |
          Set-Location -LiteralPath ${{ github.workspace }}/build_native_root/catboost/tools
          foreach($tool in 'limited_precision_dsv_diff','limited_precision_json_diff','model_comparator') {
            New-Item -Path $tool -ItemType Directory
            Move-Item "${{ github.workspace }}/build_native_root/${tool}*" -Destination $tool
          }

      - name: Run pytest
        shell: pwsh
        run: |
          python -m pip install testpath pytest 'numpy<2.0' pandas catboost
          $Env:CMAKE_SOURCE_DIR = Join-Path ${{ github.workspace }} catboost
          $Env:CMAKE_BINARY_DIR = Join-Path ${{ github.workspace }} build_native_root
          $Env:TEST_OUTPUT_DIR = Join-Path ${{ github.workspace }} test_output_pytest
          $Env:HAVE_CUDA = 0
          Set-Location -LiteralPath ${{ github.workspace }}/catboost/catboost/pytest
          python -m pytest

      - name: Run python package tests
        shell: pwsh
        run: |
          python -m pip install testpath pytest 'numpy<2.0' pandas ipywidgets scikit-learn
          $Env:CMAKE_SOURCE_DIR = Join-Path ${{ github.workspace }} catboost
          $Env:CMAKE_BINARY_DIR = Join-Path ${{ github.workspace }} build_native_root
          $Env:TEST_OUTPUT_DIR = Join-Path ${{ github.workspace }} test_output_pytest
          Set-Location -LiteralPath ${{ github.workspace }}/catboost/catboost/python-package/ut/medium
          python -m pytest
